# Database container

FROM mcr.microsoft.com/mssql/server:2019-latest

ENV MSSQL_SA_PASSWORD=\#maslO!23
ENV ACCEPT_EULA=Y

COPY ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 2137

CMD ["/opt/mssql/bin/sqlservr"]